apiVersion: v1
kind: PersistentVolume
metadata:
  name: ibankingpv
spec:
  storageClassName: ibankingStorageClass
  capacity:
    storage: 2Gi
  accessMode:
    - ReadWriteMultiple
  hostPath:
    path: "/u01/data"
