apiVersion: v1
kind: PersistentVolume
metadata:
  name: ibankingpv
spec:
  storageClassName: ibankingStorageClass
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/u01/data"
